// Real browser passkey ceremony; Chromium's virtual device signs the challenge.
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const ui = require("./ui_contracts.cjs");
module.exports = async (owner, origin, output, password) => {
  const page = await owner.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  const cdp = await owner.newCDPSession(page);
  await cdp.send("WebAuthn.enable");
  const {authenticatorId} = await cdp.send("WebAuthn.addVirtualAuthenticator", {options:{protocol:"ctap2",transport:"internal",hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
  const report = {journey:[],measurements:[],accessibility:[]};
  await page.route(origin+"/__ui_fixture/axe.js",r=>r.fulfill({contentType:"text/javascript",body:fs.readFileSync(path.join(__dirname,"../frontend/node_modules/axe-core/axe.min.js"))}));
  await page.route(origin+"/__ui_fixture/operations-spacing.css",r=>r.fulfill({contentType:"text/css",body:"body * {line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}p{margin-bottom:2em!important}"}));
  const measure=async name=>{
    await page.waitForLoadState("load");
    for(const width of [320,768,1440]) {
      await page.setViewportSize({width,height:1000});
      await page.evaluate(()=>{scrollTo(0,0);return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});
      const m=await ui.geometry(page);assert.deepEqual(m.failures,[],`${name} at ${width}: ${m.failures.join("; ")}`);
      report.measurements.push({surface:name,state:"normal",...m});
      await page.screenshot({path:path.join(output,`operations-${name}-${width}.png`),fullPage:true});
      const style=await page.addStyleTag({url:origin+"/__ui_fixture/operations-spacing.css"});
      const spaced=await ui.geometry(page);assert.deepEqual(spaced.failures,[],`${name} text spacing at ${width}`);
      report.measurements.push({surface:name,state:"text-spacing",...spaced});await style.evaluate(n=>n.remove());
    }
    await ui.accessibility(page,origin,name,report);
    await page.locator(".skip").focus();
    await page.keyboard.press("Tab");
    assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),"BODY","Keyboard reaches a control");
  };

  try {
    await page.goto(origin+"/admin/media");
    await page.getByLabel("Image",{exact:true}).setInputFiles(path.join(__dirname,"../tests/fixtures/green.png"));
    await page.locator('form[action="/admin/media"]').getByLabel("Visibility",{exact:true}).selectOption("private");
    await page.locator('form[action="/admin/media"]').getByLabel("Alternative text",{exact:true}).fill("Native AVIF fixture");
    await Promise.all([page.waitForNavigation(),page.getByRole("button",{name:"Upload image",exact:true}).click()]);
    const source=await page.locator(".media-card").filter({has:page.locator('input[name="alt"][value="Native AVIF fixture"]')}).locator("img").getAttribute("src");
    const avif=await page.evaluate(async source=>{ const image=new Image();image.src=source+"/resize/320/avif";await image.decode();return {width:image.naturalWidth,height:image.naturalHeight}; },source);
    assert(avif.width>0 && avif.height>0,"browser decodes native AVIF");
    const anonymous=await owner.browser().newContext();
    assert.equal((await anonymous.request.get(origin+source+"/resize/320/avif")).status(),401,"cached derivative requires current authority");
    await anonymous.close();
    report.journey.push("Native AVIF decodes in browser and retains private source authority");
    await page.goto(origin+"/admin/operations");
    await page.getByRole("heading",{name:"Background work",exact:true}).waitFor();
    await page.waitForFunction(()=>document.querySelector("main").textContent.includes("succeeded"));
    const background=page.locator("section").filter({has:page.getByRole("heading",{name:"Background work",exact:true})});
    await background.locator("summary").first().click();
    await background.getByText(/publication · completed/).first().waitFor();
    report.journey.push("Owner reviews durable background-stage outcome and timing");
    await measure("operations");
    await Promise.all([page.waitForNavigation(),page.getByRole("button",{name:"Inspect stored-file integrity",exact:true}).click()]);
    await page.getByRole("heading",{name:"Stored-file inspection",exact:true}).waitFor();
    await measure("integrity");
    await page.goto(origin+"/admin/operations");
    await Promise.all([page.waitForNavigation(),page.getByRole("button",{name:"Preview unused media cleanup",exact:true}).click()]);
    await page.getByRole("heading",{name:"Cleanup preview",exact:true}).waitFor();
    await measure("cleanup-preview");
    await Promise.all([page.waitForNavigation(),page.getByRole("button",{name:"Permanently remove listed files and expired sessions",exact:true}).click()]);
    await page.getByRole("heading",{name:"Cleanup result",exact:true}).waitFor();
    await measure("cleanup-result");
    assert.equal((await owner.request.get(origin+source)).status(),404,"unreferenced source is no longer served");
    report.journey.push("Owner inspects reference-aware cleanup and removes unused media");
    await page.goto(origin+"/admin/operations/audit");
    await measure("audit");
    await page.goto(origin+'/account/privacy');
    await measure('privacy-account');
    // Same-page request form has no explicit action; select its button's enclosing form.
    const ownRequest=page.getByRole('button',{name:'Send data request',exact:true}).locator('..');
    await ownRequest.getByLabel('Request type').selectOption('erase');
    await ownRequest.getByLabel('Current password',{exact:true}).fill(password);
    await Promise.all([page.waitForNavigation({waitUntil:'load'}),ownRequest.getByRole('button',{name:'Send data request',exact:true}).click()]);
    await page.getByRole('heading',{name:'erase · requested',exact:true}).waitFor();
    await measure('privacy-request-pending');
    const exportForm=page.locator('form[action="/account/privacy/export"]');
    await exportForm.getByLabel('Current password',{exact:true}).fill(password);
    const [download]=await Promise.all([page.waitForEvent('download'),exportForm.getByRole('button',{name:'Download my data',exact:true}).click()]);
    const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
    assert.equal(exported.format,'wpalt-personal-data-v1');
    assert.equal(exported.account_linked_records.users.length,1);
    assert(!JSON.stringify(exported).includes('password_hash'));
    await page.goto(origin+'/admin/privacy');
    await measure('privacy-owner-queue');
    await page.getByRole('link',{name:'Site owner · erase',exact:true}).click();
    await measure('privacy-review');
    const erasure=page.locator('form[action$="/erase-account"]');
    await erasure.getByLabel('Removal and retention explanation',{exact:true}).fill('The last owner must remain available.');
    await erasure.getByRole('checkbox').check();
    await erasure.getByRole('button',{name:'Remove account identity and profile',exact:true}).click();
    await erasure.getByRole('alert').filter({hasText:'The last site owner cannot be removed'}).waitFor();
    assert.equal(await erasure.getByLabel('Removal and retention explanation',{exact:true}).inputValue(),'The last owner must remain available.');
    assert.equal(await erasure.getByRole('button',{name:'Remove account identity and profile',exact:true}).isEnabled(),true);
    await measure('privacy-last-owner-error');
    await page.getByLabel('Decision',{exact:true}).selectOption('partial');
    await page.getByLabel('Response for the requester',{exact:true}).fill('Local records reviewed. Independent recovery copies and financial records need separately recorded retention handling.');
    await Promise.all([page.waitForNavigation({waitUntil:'load'}),page.getByRole('button',{name:'Record reviewed decision',exact:true}).click()]);
    await page.goto(origin+'/account/privacy');
    await page.getByRole('heading',{name:'erase · partial',exact:true}).waitFor();
    await page.getByText('Local records reviewed. Independent recovery copies and financial records need separately recorded retention handling.',{exact:true}).waitFor();
    await measure('privacy-request-resolved');
    report.journey.push('Verified account download, durable erasure request, owner retention decision and requester response');
    await page.goto(origin + "/account/security");
    const register = page.locator('[data-passkey="register"]');
    await register.getByLabel("Current password", {exact:true}).fill(password);
    const finish = page.waitForResponse(r => r.url().endsWith("/account/passkeys/finish"), {timeout:15000});
    await register.getByRole("button",{name:"Register a passkey"}).click();
    assert.equal((await finish).status(), 200);
    await page.waitForURL(origin + "/account/security");
    await page.getByRole("button",{name:"Remove passkey & revoke sessions"}).waitFor();
    report.journey.push("User-verified local passkey registration");
    await measure("account-security");
    await owner.clearCookies();
    await page.goto(origin + "/login");
    await page.getByLabel("Passkey account",{exact:true}).fill("owner@example.test");
    const signedIn = page.waitForResponse(r=>r.url().endsWith("/passkeys/login/finish"));
    await page.getByRole("button",{name:"Use a passkey"}).click();
    const accepted = await signedIn;
    assert.equal(accepted.status(),200);
    await page.waitForURL(origin + "/admin");
    const replay = await page.evaluate(async body => {
      const r=await fetch("/passkeys/login/finish",{method:"POST",headers:{"content-type":"application/json"},body}); return r.status;
    },accepted.request().postData());
    assert.equal(replay,403,"Signed challenge can be consumed only once");
    await page.waitForURL(origin + "/admin");
    report.journey.push("Real browser signature signs in without password");
    await page.goto(origin + "/account/security");
    const remove = page.locator('form[action="/account/passkeys/remove"]');
    await remove.getByLabel("Current password",{exact:true}).fill(password);
    await Promise.all([page.waitForNavigation(),remove.getByRole("button").click()]);
    assert.equal(await page.locator('form[action="/account/passkeys/remove"]').count(),0);
    const denied = await page.evaluate(async origin => {
      const r = await fetch(origin + "/passkeys/login/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:"owner@example.test"})});return r.status;
    },origin);
    assert.equal(denied,403);
    report.journey.push("Removed key cannot begin a new sign-in");
    assert.deepEqual(errors,[]);
    const cookieReport = await require("./cookie_scan.cjs")(owner.browser(),origin,["/","/about"]);
    assert.equal(cookieReport.pages.length,2);
    assert.deepEqual(cookieReport.blocked_external_origins,[]);
    assert.ok(!JSON.stringify(cookieReport).includes(password),"Cookie report contains no credential values");
    report.cookie_scan=cookieReport;
    report.status="passed";
  } finally {
    await cdp.send("WebAuthn.removeVirtualAuthenticator",{authenticatorId});
    await page.close();
    fs.writeFileSync(path.join(output,"operations-result.json"),JSON.stringify(report,null,2));
  }
};
