use clap::{Parser, Subcommand};
use fs2::FileExt;
use std::{io::Read, path::PathBuf};
use wpalt::{
    App, auth, backup,
    config::Config,
    content,
    model::{PostInput, Session, User},
};

#[derive(Parser)]
#[command(
    version,
    about = "Owner-controlled publishing, from one Rust application"
)]
struct Cli {
    #[arg(long, global = true)]
    config: Option<PathBuf>,
    #[arg(long, global = true)]
    database_url: Option<String>,
    #[arg(long, global = true)]
    data_dir: Option<PathBuf>,
    #[arg(long, global = true)]
    listen: Option<std::net::SocketAddr>,
    #[arg(long, global = true)]
    base_url: Option<String>,
    #[arg(long, global = true)]
    debug: bool,
    #[command(subcommand)]
    command: Command,
}
#[derive(Subcommand)]
enum Command {
    /// Initialize a site. Read the initial password from stdin, never an argv flag.
    Init {
        #[arg(long)]
        admin_email: String,
        #[arg(long, default_value = "Site owner")]
        admin_name: String,
    },
    /// Run the web server and durable publication scheduler.
    Serve,
    /// Show validated effective configuration with credentials redacted.
    Config,
    /// Create an offline database-and-media snapshot in a new private file.
    Backup {
        output: PathBuf,
        /// Encrypt with a private recovery-key file generated by recovery-key.
        #[arg(long)]
        key_file: Option<PathBuf>,
    },
    /// Generate a private recovery key. Store an independent copy offline.
    RecoveryKey { output: PathBuf },
    /// Create and verify encrypted copies in configured recovery destinations.
    RecoveryRun,
    /// Inspect durable recovery copy and interruption status.
    RecoveryStatus,
    /// Verify a separately retained encrypted recovery point before replacing the executable.
    UpgradePrepare {
        output: PathBuf,
        #[arg(long)]
        key_file: PathBuf,
    },
    /// Native PostgreSQL 17 archive_command helper; independent of the app process lock.
    WalStore { input: PathBuf, name: String },
    /// Native PostgreSQL 17 restore_command helper; replaces the engine output atomically.
    WalRestore { name: String, output: PathBuf },
    /// Scan stored media/private attachment inventory without changing files.
    IntegrityScan {
        #[arg(long, default_value = "")]
        after_image: String,
        #[arg(long, default_value = "")]
        after_attachment: String,
    },
    /// Convert a bounded owner-selected MP4/WebM source into a new private MP4.
    VideoTranscode { input: PathBuf, output: PathBuf },
    /// Read bounded private background-cycle history while the server is stopped.
    JobHistory,
    /// Export bounded account-linked personal data into a NEW private file, while stopped.
    PrivacyExport { user_id: String, output: PathBuf },
    /// Preview unused media and expired sessions; deletion requires the exact recent plan.
    Cleanup {
        #[arg(long)]
        execute: Option<String>,
        #[arg(long)]
        cutoff: Option<i64>,
    },
    /// Validate a full recovery graph without restoring it.
    RecoveryInspect {
        input: PathBuf,
        #[arg(long)]
        key_file: Option<PathBuf>,
    },
    /// Preview dependency-aware editorial selection; publish a NEW private package with --execute PLAN --output FILE.
    RecoverySelect {
        input: PathBuf,
        #[arg(long = "post", required = true)]
        posts: Vec<String>,
        #[arg(long)]
        key_file: Option<PathBuf>,
        #[arg(long, requires = "output")]
        execute: Option<String>,
        #[arg(long, requires = "execute")]
        output: Option<PathBuf>,
    },
    /// Preview a read-only URL-aware clone package; create a NEW package using the exact --execute plan.
    RecoveryClone {
        input: PathBuf,
        #[arg(long)]
        source_origin: String,
        #[arg(long)]
        key_file: Option<PathBuf>,
        #[arg(long, requires = "output")]
        execute: Option<String>,
        #[arg(long, requires = "execute")]
        output: Option<PathBuf>,
    },
    /// Activate a recovered clone after reviewing source ownership and all side-effect queues, while stopped.
    CloneActivate {
        #[arg(long)]
        review: String,
    },
    /// Extract one validated media/private attachment as a new private file.
    RecoveryFile {
        input: PathBuf,
        id: String,
        output: PathBuf,
        #[arg(long)]
        key_file: Option<PathBuf>,
    },
    /// Migrate an M6 plaintext archive to current format, preserving its data.
    MigrateBackup { input: PathBuf, output: PathBuf },
    /// Preview unused encrypted chunks; --execute requires the preview plan hash.
    RecoveryPrune {
        destination: PathBuf,
        key_file: PathBuf,
        #[arg(long)]
        execute: Option<String>,
    },
    /// Emergency local host-owner recovery. Server must be stopped.
    AuthReset {
        #[arg(long)]
        email: String,
    },
    /// Restore a snapshot into an EMPTY database/data directory, with the server stopped.
    Restore {
        input: PathBuf,
        #[arg(long)]
        key_file: Option<PathBuf>,
    },
    /// Add an account while the server is stopped. Password is read from stdin.
    UserAdd {
        #[arg(long)]
        email: String,
        #[arg(long)]
        name: String,
        #[arg(long, default_value = "editor")]
        role: String,
    },
    /// Offline portable theme operations, using the same validation as the studio.
    Theme {
        #[command(subcommand)]
        command: ThemeCommand,
    },
    /// Offline membership and course operations using the shared policy engine.
    Member {
        #[command(subcommand)]
        command: MemberCommand,
    },
    /// Offline commerce setup, reconciliation and maintenance.
    Shop {
        #[command(subcommand)]
        command: ShopCommand,
    },
    /// Populate an initialized empty site with reviewable example content.
    SeedDemo {
        #[arg(long, default_value_t = 8)]
        posts: u32,
    },
}
#[derive(Subcommand)]
enum ShopCommand {
    ProductImport {
        input: PathBuf,
        #[arg(long)]
        id: Option<String>,
        #[arg(long, default_value_t = 0)]
        version: i64,
    },
    VariantImport {
        product: String,
        input: PathBuf,
        #[arg(long)]
        id: Option<String>,
        #[arg(long, default_value_t = 0)]
        version: i64,
    },
    DiscountImport {
        input: PathBuf,
        #[arg(long, default_value_t = 0)]
        version: i64,
    },
    Resource {
        title: String,
        #[arg(long, default_value = "")]
        staff: String,
    },
    SlotImport {
        input: PathBuf,
    },
    Payment {
        order: String,
        reference: String,
    },
    Refund {
        order: String,
        input: PathBuf,
    },
    RefundConfirm {
        refund: String,
        reference: String,
    },
    Fulfill {
        order: String,
    },
    Rules {
        #[arg(long)]
        tax_bps: i64,
        #[arg(long)]
        shipping_minor: i64,
        #[arg(long)]
        tax_shipping: bool,
    },
    Maintenance,
    Report,
    SeedDemo,
}
async fn shop_command(app: &App, command: ShopCommand) -> wpalt::error::Result<()> {
    use sqlx::Row;
    use wpalt::{commerce as c, error::Error};
    let r = sqlx::query(
        "SELECT id,email,name,role FROM users WHERE role='admin' ORDER BY created_at,id LIMIT 1",
    )
    .fetch_optional(&app.db.pool)
    .await?
    .ok_or_else(Error::not_found)?;
    let s = Session {
        user: User {
            id: r.get("id"),
            email: r.get("email"),
            name: r.get("name"),
            role: r.get("role"),
        },
        csrf: String::new(),
        hash: String::new(),
    };
    c::owner(app, &s).await?;
    match command {
        ShopCommand::ProductImport { input, id, version } => {
            let bytes = backup::read_bounded(&input, 32768).await?;
            let p = serde_json::from_slice(&bytes)
                .map_err(|_| Error::invalid("Invalid product JSON."))?;
            println!(
                "{}",
                c::catalog::save_product(app, &s, id.as_deref(), version, &p).await?
            );
        }
        ShopCommand::VariantImport {
            product,
            input,
            id,
            version,
        } => {
            let bytes = backup::read_bounded(&input, 32768).await?;
            let v = serde_json::from_slice(&bytes)
                .map_err(|_| Error::invalid("Invalid variant JSON."))?;
            println!(
                "{}",
                c::catalog::save_variant(app, &s, &product, id.as_deref(), version, &v).await?
            );
        }
        ShopCommand::DiscountImport { input, version } => {
            let bytes = backup::read_bounded(&input, 32768).await?;
            let d = serde_json::from_slice(&bytes)
                .map_err(|_| Error::invalid("Invalid discount JSON."))?;
            c::catalog::discount(app, &s, &d, version).await?;
            println!("Discount saved.");
        }
        ShopCommand::Resource { title, staff } => {
            println!("{}", c::booking::resource(app, &s, &title, &staff).await?)
        }
        ShopCommand::SlotImport { input } => {
            let bytes = backup::read_bounded(&input, 32768).await?;
            let i =
                serde_json::from_slice(&bytes).map_err(|_| Error::invalid("Invalid slot JSON."))?;
            println!("{}", c::booking::slot(app, &s, &i).await?);
        }
        ShopCommand::Payment { order, reference } => {
            let v = sqlx::query_scalar("SELECT version FROM shop_orders WHERE id=$1")
                .bind(&order)
                .fetch_one(&app.db.pool)
                .await?;
            c::orders::record_offline(app, &s, &order, v, &reference).await?;
            println!("Actual payment recorded.");
        }
        ShopCommand::Refund { order, input } => {
            let bytes = backup::read_bounded(&input, 32768).await?;
            let i = serde_json::from_slice(&bytes)
                .map_err(|_| Error::invalid("Invalid refund JSON."))?;
            let v = sqlx::query_scalar("SELECT version FROM shop_orders WHERE id=$1")
                .bind(&order)
                .fetch_one(&app.db.pool)
                .await?;
            println!(
                "{}",
                c::orders::refund_request(app, &s, &order, v, &i).await?
            );
        }
        ShopCommand::RefundConfirm { refund, reference } => {
            let a = sqlx::query_scalar("SELECT amount_minor FROM shop_refunds WHERE id=$1")
                .bind(&refund)
                .fetch_one(&app.db.pool)
                .await?;
            c::orders::record_offline_refund(app, &s, &refund, &reference, a).await?;
            println!("Actual refund recorded.");
        }
        ShopCommand::Fulfill { order } => {
            let v = sqlx::query_scalar("SELECT version FROM shop_orders WHERE id=$1")
                .bind(&order)
                .fetch_one(&app.db.pool)
                .await?;
            c::orders::fulfill(app, &s, &order, v).await?;
            println!("Fulfillment recorded.");
        }
        ShopCommand::Rules {
            tax_bps,
            shipping_minor,
            tax_shipping,
        } => {
            let v = c::settings(app).await?.get("version");
            c::catalog::set_rules(app, &s, v, tax_bps, shipping_minor, tax_shipping).await?;
            println!("Store rules saved.");
        }
        ShopCommand::Maintenance => println!(
            "{} commerce transitions processed; no offline payment was fabricated.",
            c::tick(app).await?
        ),
        ShopCommand::Report => {
            let r=sqlx::query("SELECT (SELECT COUNT(*) FROM shop_products) AS products,(SELECT COUNT(*) FROM shop_orders WHERE payment_state='awaiting') AS awaiting,(SELECT COUNT(*) FROM shop_orders WHERE payment_state='needs_refund') AS needs_refund,(SELECT COUNT(*) FROM shop_subscriptions WHERE state='past_due') AS past_due,(SELECT COUNT(*) FROM shop_subscriptions WHERE provider_cancel_pending=1) AS pending_billing_stop,(SELECT records FROM shop_usage WHERE id=1) AS records").fetch_one(&app.db.pool).await?;
            println!(
                "{}",
                serde_json::json!({"currency":app.config.commerce.currency,"products":r.get::<i64,_>("products"),"awaiting_payment":r.get::<i64,_>("awaiting"),"needs_refund":r.get::<i64,_>("needs_refund"),"past_due":r.get::<i64,_>("past_due"),"pending_billing_stop":r.get::<i64,_>("pending_billing_stop"),"records":r.get::<i64,_>("records")})
            );
        }
        ShopCommand::SeedDemo => {
            let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM shop_products")
                .fetch_one(&app.db.pool)
                .await?;
            if count != 0 {
                return Err(Error::invalid("Commerce demo requires an empty catalog."));
            }
            let mut booking = None;
            for (kind, title, price, stock, interval) in [
                ("physical", "Field notebook", 1800, 20, ""),
                ("digital", "Independent publishing guide", 900, -1, ""),
                ("membership", "Studio membership", 2500, -1, "month"),
                ("booking", "Editorial consultation", 6000, -1, ""),
            ] {
                let id=c::catalog::save_product(app,&s,None,0,&c::catalog::ProductInput{slug:kind.into(),title:title.into(),description:"Synthetic demonstration. Clear terms, local records, no external payment required.".into(),kind:kind.into(),entitlement:if kind=="membership"{"studio".into()}else{String::new()},access_seconds:0,download_id:String::new(),published:true}).await?;
                let v = c::catalog::save_variant(
                    app,
                    &s,
                    &id,
                    None,
                    0,
                    &c::catalog::VariantInput {
                        title: "Standard".into(),
                        sku: format!("DEMO-{kind}"),
                        price_minor: price,
                        member_price_minor: -1,
                        member_key: String::new(),
                        stock_total: stock,
                        billing_interval: interval.into(),
                        active: true,
                    },
                )
                .await?;
                if kind == "booking" {
                    booking = Some(v)
                }
            }
            let resource = c::booking::resource(app, &s, "Editorial studio", &s.user.id).await?;
            c::booking::slot(
                app,
                &s,
                &c::booking::SlotInput {
                    resource_id: resource,
                    variant_id: booking.unwrap(),
                    starts_at: wpalt::now() + 3 * 86400,
                    ends_at: wpalt::now() + 3 * 86400 + 3600,
                    capacity: 4,
                },
            )
            .await?;
            println!(
                "Four sample products and one reservation slot created. Visit /shop and /admin/shop."
            );
        }
    }
    Ok(())
}
#[derive(Subcommand)]
enum ThemeCommand {
    Import {
        id: String,
        input: PathBuf,
        #[arg(long)]
        publish: bool,
    },
    Export {
        id: String,
        output: PathBuf,
        #[arg(long)]
        draft: bool,
    },
    Publish {
        id: String,
    },
    Activate {
        id: String,
    },
}
#[derive(Subcommand)]
enum MemberCommand {
    Policy {
        #[arg(long)]
        title: String,
        #[arg(long, default_value = "")]
        entitlement: String,
        #[arg(long, default_value = "")]
        group: String,
    },
    Grant {
        #[arg(long)]
        email: String,
        #[arg(long)]
        entitlement: String,
        #[arg(long)]
        starts: Option<i64>,
        #[arg(long, default_value_t = 0)]
        expires: i64,
        #[arg(long, default_value = "local-cli")]
        origin: String,
    },
    Revoke {
        id: String,
    },
    Protect {
        #[arg(long)]
        kind: String,
        #[arg(long)]
        resource: String,
        #[arg(long)]
        policy: String,
        #[arg(long, default_value_t = 0)]
        opens: i64,
        #[arg(long, default_value_t = 0)]
        delay: i64,
    },
    Release {
        #[arg(long)]
        kind: String,
        #[arg(long)]
        resource: String,
    },
    CourseImport {
        input: PathBuf,
        #[arg(long)]
        id: Option<String>,
        #[arg(long)]
        publish: bool,
    },
    CourseExport {
        id: String,
        output: PathBuf,
        #[arg(long)]
        draft: bool,
    },
    IdentityBind {
        #[arg(long)]
        email: String,
        #[arg(long)]
        issuer: String,
        #[arg(long)]
        subject: String,
    },
}
async fn member_command(app: &App, command: MemberCommand) -> wpalt::error::Result<()> {
    use wpalt::{error::Error, membership as m};
    match command {
        MemberCommand::Policy {
            title,
            entitlement,
            group,
        } => println!("{}", m::policy(app, &title, &entitlement, &group).await?),
        MemberCommand::Grant {
            email,
            entitlement,
            starts,
            expires,
            origin,
        } => {
            let id: String =
                sqlx::query_scalar("SELECT id FROM users WHERE email=$1 AND role<>'disabled'")
                    .bind(email.to_ascii_lowercase())
                    .fetch_optional(&app.db.pool)
                    .await?
                    .ok_or_else(Error::not_found)?;
            println!(
                "{}",
                m::grant(
                    app,
                    &id,
                    &entitlement,
                    starts.unwrap_or_else(wpalt::now),
                    expires,
                    &origin
                )
                .await?
            );
        }
        MemberCommand::Revoke { id } => {
            m::uuid(&id)?;
            if sqlx::query("UPDATE member_grants SET revoked=1,version=version+1 WHERE id=$1")
                .bind(id)
                .execute(&app.db.pool)
                .await?
                .rows_affected()
                != 1
            {
                return Err(Error::not_found());
            }
            println!("Membership revoked.");
        }
        MemberCommand::Protect {
            kind,
            resource,
            policy,
            opens,
            delay,
        } => {
            m::protect(app, &kind, &resource, &policy, opens, delay).await?;
            println!("Resource protected.");
        }
        MemberCommand::Release { kind, resource } => {
            m::release(app, &kind, &resource).await?;
            println!("Access rule released.");
        }
        MemberCommand::CourseImport { input, id, publish } => {
            let bytes = backup::read_bounded(&input, 256 * 1024).await?;
            let c: m::Course = serde_json::from_slice(&bytes)
                .map_err(|_| Error::invalid("Invalid course file."))?;
            c.validate()?;
            let id = match id {
                Some(id) => {
                    m::uuid(&id)?;
                    id
                }
                None => m::create_course(app, &c).await?,
            };
            let version: i64 = sqlx::query_scalar("SELECT version FROM member_courses WHERE id=$1")
                .bind(&id)
                .fetch_optional(&app.db.pool)
                .await?
                .ok_or_else(Error::not_found)?;
            m::save_course(app, &id, version, &c, publish).await?;
            println!("{id}");
        }
        MemberCommand::CourseExport { id, output, draft } => {
            let sql = if draft {
                "SELECT draft FROM member_courses WHERE id=$1"
            } else {
                "SELECT live FROM member_courses WHERE id=$1 AND published_version>0"
            };
            let raw: String = sqlx::query_scalar(sql)
                .bind(id)
                .fetch_optional(&app.db.pool)
                .await?
                .ok_or_else(Error::not_found)?;
            backup::write_private(&output, raw.as_bytes())
                .map_err(|_| Error::invalid("Cannot create a new private course export."))?;
            println!("Course exported.");
        }
        MemberCommand::IdentityBind {
            email,
            issuer,
            subject,
        } => {
            let url = url::Url::parse(&issuer).map_err(|_| Error::invalid("Invalid issuer."))?;
            if url.scheme() != "https" || subject.is_empty() || subject.len() > 255 {
                return Err(Error::invalid("Use an HTTPS issuer and a stable subject."));
            }
            let id: String =
                sqlx::query_scalar("SELECT id FROM users WHERE email=$1 AND role<>'disabled'")
                    .bind(email.to_ascii_lowercase())
                    .fetch_optional(&app.db.pool)
                    .await?
                    .ok_or_else(Error::not_found)?;
            sqlx::query("INSERT INTO member_identities(issuer,subject,user_id) VALUES($1,$2,$3)")
                .bind(issuer)
                .bind(subject)
                .bind(id)
                .execute(&app.db.pool)
                .await?;
            println!("Identity bound.");
        }
    }
    Ok(())
}
fn password() -> anyhow::Result<String> {
    let mut value = String::new();
    std::io::stdin().take(258).read_to_string(&mut value)?;
    let password = value.trim_end_matches(['\r', '\n']).to_owned();
    anyhow::ensure!(
        (12..=256).contains(&password.len()),
        "password from stdin must be 12..256 bytes"
    );
    Ok(password)
}
fn lock(config: &Config) -> anyhow::Result<std::fs::File> {
    config.prepare_directories()?;
    let mut options = std::fs::OpenOptions::new();
    options.create(true).read(true).write(true).truncate(false);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let file = options.open(config.data_dir.join(".wpalt.lock"))?;
    file.try_lock_exclusive().map_err(|_| {
        anyhow::anyhow!(
            "this data directory is already in use; stop the server before offline operations"
        )
    })?;
    Ok(file)
}
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    if let Command::RecoveryKey { output } = &cli.command {
        let key = wpalt::operations::encryption::generate_key();
        backup::write_private(output, hex::encode(key).as_bytes())?;
        println!(
            "Recovery key created. Keep an independent offline copy; loss makes encrypted backups unrecoverable."
        );
        return Ok(());
    }

    let mut config = Config::load(cli.config.as_deref())?;
    if let Some(v) = cli.database_url {
        config.database_url = v;
    }
    if let Some(v) = cli.data_dir {
        config.data_dir = v;
    }
    if let Some(v) = cli.listen {
        config.listen = v;
    }
    if let Some(v) = cli.base_url {
        config.base_url = v;
    }
    if cli.debug {
        config.debug = true;
    }
    config.validate()?;
    if matches!(cli.command, Command::Config) {
        println!("{}", serde_json::to_string_pretty(&config.redacted())?);
        return Ok(());
    }
    // Portable recovery tools operate on files/config only: no live server,
    // database, site lock, installation or vendor account is needed.
    match &cli.command {
        Command::WalStore { input, name } => {
            wpalt::operations::postgres_archive::store(&config, input, name)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("WAL stored and verified.");
            return Ok(());
        }
        Command::WalRestore { name, output } => {
            wpalt::operations::postgres_archive::restore(&config, name, output)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("Authenticated WAL restored.");
            return Ok(());
        }
        Command::RecoveryInspect { input, key_file } => {
            let bytes = recovery_bytes(&config, input, key_file.as_deref()).await?;
            println!(
                "{}",
                serde_json::to_string_pretty(
                    &backup::inspect(&config, &bytes).map_err(|e| anyhow::anyhow!(e.1))?
                )?
            );
            return Ok(());
        }
        Command::RecoveryFile {
            input,
            id,
            output,
            key_file,
        } => {
            let bytes = recovery_bytes(&config, input, key_file.as_deref()).await?;
            backup::extract_file(&config, &bytes, id, output).map_err(|e| anyhow::anyhow!(e.1))?;
            println!("Recovered a new private file.");
            return Ok(());
        }
        Command::RecoverySelect {
            input,
            posts,
            key_file,
            execute,
            output,
        } => {
            let bytes = recovery_bytes(&config, input, key_file.as_deref()).await?;
            let prepared = backup::selection::prepare(&config, &bytes, posts)
                .map_err(|e| anyhow::anyhow!(e.1))?;
            if let Some(plan) = execute {
                anyhow::ensure!(
                    *plan == prepared.plan,
                    "Selection plan changed; inspect a fresh preview before creating the package."
                );
                backup::write_private(
                    output.as_ref().expect("clap requires output"),
                    &prepared.bytes,
                )?;
            }
            println!("{}", serde_json::to_string_pretty(&prepared.report)?);
            return Ok(());
        }
        Command::RecoveryClone {
            input,
            source_origin,
            key_file,
            execute,
            output,
        } => {
            let bytes = recovery_bytes(&config, input, key_file.as_deref()).await?;
            let prepared = backup::selection::clone_package(&config, &bytes, source_origin)
                .map_err(|e| anyhow::anyhow!(e.1))?;
            if let Some(plan) = execute {
                anyhow::ensure!(
                    *plan == prepared.plan,
                    "Clone plan changed; inspect a fresh preview."
                );
                backup::write_private(
                    output.as_ref().expect("clap requires output"),
                    &prepared.bytes,
                )?;
            }
            println!("{}", serde_json::to_string_pretty(&prepared.report)?);
            return Ok(());
        }
        Command::MigrateBackup { input, output } => {
            let bytes = backup::read_bounded(input, config.max_backup_bytes)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            let bytes = backup::migrate_m6(&config, &bytes).map_err(|e| anyhow::anyhow!(e.1))?;
            backup::write_private(output, &bytes)?;
            println!("Migrated a new private archive.");
            return Ok(());
        }
        _ => {}
    }
    tracing_subscriber::fmt()
        .json()
        .with_env_filter(if config.debug {
            "wpalt=debug,sqlx=debug"
        } else {
            "wpalt=info,sqlx=warn"
        })
        .with_writer(std::io::stderr)
        .init();
    let _lock = lock(&config)?;
    let app = App::open(config).await?;
    anyhow::ensure!(
        !app.clone_held.load(std::sync::atomic::Ordering::SeqCst)
            || matches!(
                cli.command,
                Command::Serve
                    | Command::CloneActivate { .. }
                    | Command::Backup { .. }
                    | Command::RecoveryStatus
                    | Command::JobHistory
                    | Command::PrivacyExport { .. }
            ),
        "This clone is held read-only. Review source shutdown, queues, payment ownership, identities and credentials before clone-activate."
    );
    // Journal command classes without collecting argv, paths or secrets.
    let route = match &cli.command {
        Command::Init { .. } => Some("cli:init"),
        Command::Backup { .. } => Some("cli:backup"),
        Command::RecoveryRun => Some("cli:recovery-run"),
        Command::UpgradePrepare { .. } => Some("cli:upgrade-prepare"),
        Command::VideoTranscode { .. } => Some("cli:video-transcode"),
        Command::PrivacyExport { .. } => Some("cli:privacy-export"),
        Command::CloneActivate { .. } => Some("cli:clone-activate"),
        Command::RecoveryPrune { .. } => Some("cli:recovery-prune"),
        Command::Cleanup {
            execute: Some(_), ..
        } => Some("cli:cleanup"),
        Command::AuthReset { .. } => Some("cli:auth-reset"),
        Command::Restore { .. } => Some("cli:restore"),
        Command::UserAdd { .. } => Some("cli:user-add"),
        Command::Theme { .. } => Some("cli:theme"),
        Command::Member { .. } => Some("cli:member"),
        Command::Shop { .. } => Some("cli:shop"),
        Command::SeedDemo { .. } => Some("cli:seed-demo"),
        _ => None,
    };
    let audit_id = uuid::Uuid::new_v4().to_string();
    let audit_app = app.clone();
    if let Some(route) = route {
        wpalt::operations::audit::append(
            &app,
            wpalt::operations::audit::Event {
                at: wpalt::now(),
                request_id: audit_id.clone(),
                actor: "host-owner".into(),
                route: route.into(),
                phase: "intent".into(),
                status: 0,
            },
        )
        .await
        .map_err(|e| anyhow::anyhow!(e.1))?;
    }
    let outcome = execute(app, cli.command).await;
    if let Some(route) = route
        && wpalt::operations::audit::append(
            &audit_app,
            wpalt::operations::audit::Event {
                at: wpalt::now(),
                request_id: audit_id,
                actor: "host-owner".into(),
                route: route.into(),
                phase: "outcome".into(),
                status: if outcome.is_ok() { 200 } else { 500 },
            },
        )
        .await
        .is_err()
    {
        // A command may already have committed money or data. Missing audit
        // persistence must not instruct operators to repeat the mutation.
        tracing::error!(event = "cli_audit_outcome_failed", route);
        eprintln!("Warning: outcome audit could not be persisted; inspect state before retrying.");
    }
    outcome
}

async fn execute(app: App, command: Command) -> anyhow::Result<()> {
    match command {
        Command::Init {
            admin_email,
            admin_name,
        } => {
            auth::initialize(&app, &admin_email, &admin_name, &password()?).await?;
            println!(
                "Site initialized. Run wpalt serve, then visit {}/login",
                app.config.origin()
            );
        }
        Command::Config => unreachable!(),
        Command::UpgradePrepare { output, key_file } => {
            let receipt = wpalt::operations::upgrade::prepare(&app, &output, &key_file)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("{}", serde_json::to_string_pretty(&receipt)?);
        }
        Command::RecoveryRun => {
            let state = wpalt::operations::recovery::run(&app)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("{}", serde_json::to_string_pretty(&state)?);
            anyhow::ensure!(
                state.copies.iter().all(|c| c.state == "verified"),
                "one or more backup copies failed"
            );
        }
        Command::RecoveryPrune {
            destination,
            key_file,
            execute,
        } => {
            let key = wpalt::operations::encryption::read_key(&key_file)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            let report = wpalt::operations::incremental::cleanup(
                &destination,
                &key,
                app.config.max_backup_bytes,
                execute.as_deref(),
            )
            .await
            .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("{}", serde_json::to_string_pretty(&report)?);
        }
        Command::WalStore { .. }
        | Command::WalRestore { .. }
        | Command::RecoveryInspect { .. }
        | Command::RecoveryFile { .. }
        | Command::RecoverySelect { .. }
        | Command::RecoveryClone { .. }
        | Command::MigrateBackup { .. } => unreachable!(),
        Command::CloneActivate { review } => {
            wpalt::operations::clone_hold::activate(&app, &review)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            println!(
                "Clone activated. Inspect and reconcile uncertain jobs; activation is not proof that external ownership transferred."
            );
        }
        Command::AuthReset { email } => {
            let mut tx = app.db.pool.begin().await?;
            let user: String =
                sqlx::query_scalar("SELECT id FROM users WHERE email=$1 AND role<>'disabled'")
                    .bind(email.to_ascii_lowercase())
                    .fetch_one(&mut *tx)
                    .await?;
            for table in ["user_factors", "user_passkeys", "sessions"] {
                sqlx::query(&format!("DELETE FROM {table} WHERE user_id=$1"))
                    .bind(&user)
                    .execute(&mut *tx)
                    .await?;
            }
            tx.commit().await?;
            tracing::warn!(event="offline_authenticator_reset",user_id=%user);
            println!(
                "Local authenticators and sessions cleared. Password sign-in remains required."
            );
        }
        Command::VideoTranscode { input, output } => {
            let source =
                backup::read_bounded(&input, app.config.max_upload_bytes.min(32 * 1024 * 1024))
                    .await
                    .map_err(|e| anyhow::anyhow!(e.1))?;
            let encoded = wpalt::operations::video::transcode(&app, &source)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            backup::write_private(&output, &encoded)?;
            println!("Created a new private bounded MP4 file.");
        }
        Command::PrivacyExport { user_id, output } => {
            let bytes = wpalt::operations::privacy::export(&app, &user_id)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            backup::write_private(&output, &bytes)?;
            println!("Created a new private account-linked data export.");
        }
        Command::JobHistory => {
            let cycles = wpalt::operations::jobs::read(&app)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("{}", serde_json::to_string_pretty(&cycles)?);
        }
        Command::Cleanup { execute, cutoff } => {
            if let Some(hash) = execute {
                let cutoff = cutoff
                    .ok_or_else(|| anyhow::anyhow!("--execute requires the preview --cutoff"))?;
                let result = wpalt::operations::cleanup::execute(&app, &hash, cutoff)
                    .await
                    .map_err(|e| anyhow::anyhow!(e.1))?;
                println!("{}", serde_json::to_string_pretty(&result)?);
            } else {
                anyhow::ensure!(cutoff.is_none(), "--cutoff is only used with --execute");
                let plan = wpalt::operations::cleanup::preview(&app)
                    .await
                    .map_err(|e| anyhow::anyhow!(e.1))?;
                println!("{}", serde_json::to_string_pretty(&plan)?);
            }
        }
        Command::IntegrityScan {
            after_image,
            after_attachment,
        } => {
            let report =
                wpalt::operations::integrity::scan_page(&app, &after_image, &after_attachment)
                    .await
                    .map_err(|e| anyhow::anyhow!(e.1))?;
            println!("{}", serde_json::to_string_pretty(&report)?);
            anyhow::ensure!(
                report.failed.is_empty() && report.pattern_warnings.is_empty() && !report.limited,
                "integrity scan found failures or reached its bounded workload; inspect the report"
            );
        }
        Command::RecoveryStatus => {
            println!(
                "{}",
                serde_json::to_string_pretty(
                    &wpalt::operations::recovery::status(&app)
                        .await
                        .map_err(|e| anyhow::anyhow!(e.1))?
                )?
            );
        }
        Command::RecoveryKey { .. } => unreachable!(),
        Command::Backup { output, key_file } => {
            let bytes = backup::capture(&app)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            let bytes = if let Some(path) = key_file {
                let key = wpalt::operations::encryption::read_key(&path)
                    .await
                    .map_err(|e| anyhow::anyhow!(e.1))?;
                wpalt::operations::encryption::seal(&key, &bytes)
                    .map_err(|e| anyhow::anyhow!(e.1))?
            } else {
                bytes
            };
            backup::write_private(&output, &bytes)?;
            println!(
                "Created private snapshot ({} bytes). Keep an independent secure copy.",
                bytes.len()
            );
        }
        Command::Restore { input, key_file } => {
            let file = std::fs::File::open(&input)?;
            anyhow::ensure!(
                file.metadata()?.len()
                    <= (app.config.max_backup_bytes + wpalt::operations::encryption::OVERHEAD)
                        as u64,
                "backup exceeds configured limit"
            );
            let mut bytes = Vec::new();
            file.take(
                (app.config.max_backup_bytes + wpalt::operations::encryption::OVERHEAD) as u64 + 1,
            )
            .read_to_end(&mut bytes)?;
            let bytes = if let Some(path) = key_file {
                let key = wpalt::operations::encryption::read_key(&path)
                    .await
                    .map_err(|e| anyhow::anyhow!(e.1))?;
                {
                    let decoded = wpalt::operations::encryption::open(
                        &key,
                        &bytes,
                        app.config.max_backup_bytes,
                    )
                    .map_err(|e| anyhow::anyhow!(e.1))?;
                    if wpalt::operations::incremental::is_manifest(&decoded) {
                        wpalt::operations::incremental::assemble(
                            input.parent().unwrap_or(std::path::Path::new(".")),
                            &key,
                            &decoded,
                            app.config.max_backup_bytes,
                        )
                        .await
                        .map_err(|e| anyhow::anyhow!(e.1))?
                    } else {
                        decoded
                    }
                }
            } else {
                bytes
            };
            backup::restore(&app, &bytes)
                .await
                .map_err(|e| anyhow::anyhow!(e.1))?;
            optimize_bulk(&app).await;
            println!("Restored site. Existing sessions are not restored; sign in again.");
        }
        Command::UserAdd { email, name, role } => {
            auth::add_user(&app, &email, &name, &role, &password()?).await?;
            println!("Account created.");
        }
        Command::Theme { command } => {
            use wpalt::{schema, theme};
            let result: wpalt::error::Result<()> = async {
                match command {
                    ThemeCommand::Import { id, input, publish } => {
                        let file = std::fs::File::open(input)?;
                        if file.metadata()?.len() > 256 * 1024 {
                            return Err(wpalt::error::Error::invalid(
                                "Theme package exceeds 256 KiB.",
                            ));
                        }
                        let mut raw = String::new();
                        file.take(256 * 1024 + 1).read_to_string(&mut raw)?;
                        let package =
                            theme::Package::parse(&raw, &schema::Registry::load(&app).await?)?;
                        let version: Option<i64> =
                            sqlx::query_scalar("SELECT version FROM themes WHERE id=$1")
                                .bind(&id)
                                .fetch_optional(&app.db.pool)
                                .await?;
                        theme::save(&app, &id, package, version.unwrap_or(0), publish).await?;
                    }
                    ThemeCommand::Export { id, output, draft } => {
                        let stored = theme::load(&app, &id, draft).await?;
                        let bytes = serde_json::to_vec_pretty(&stored.package)
                            .map_err(|_| wpalt::error::Error::invalid("Invalid theme."))?;
                        backup::write_private(&output, &bytes).map_err(|_| {
                            wpalt::error::Error::invalid("Cannot create a new private export file.")
                        })?;
                    }
                    ThemeCommand::Publish { id } => {
                        let stored = theme::load(&app, &id, true).await?;
                        theme::save(&app, &id, stored.package, stored.version, true).await?;
                    }
                    ThemeCommand::Activate { id } => theme::activate(&app, &id).await?,
                }
                Ok(())
            }
            .await;
            result.map_err(|e| anyhow::anyhow!(e.1))?;
            println!("Theme operation completed.");
        }
        Command::Shop { command } => shop_command(&app, command)
            .await
            .map_err(|e| anyhow::anyhow!(e.1))?,
        Command::Member { command } => member_command(&app, command)
            .await
            .map_err(|e| anyhow::anyhow!(e.1))?,
        Command::SeedDemo { posts } => seed(&app, posts).await?,
        Command::Serve => {
            app.db.settings().await.map_err(|_| {
                anyhow::anyhow!("site is not initialized; run wpalt init or restore first")
            })?;
            let scheduled = app.clone();
            let job = tokio::spawn(async move {
                let mut interval = tokio::time::interval(std::time::Duration::from_secs(
                    scheduled.config.scheduler_seconds,
                ));
                interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
                loop {
                    interval.tick().await;
                    if scheduled
                        .clone_held
                        .load(std::sync::atomic::Ordering::SeqCst)
                    {
                        continue;
                    }
                    use wpalt::operations::jobs::{run_cycle, stage, stage_unit};
                    if run_cycle(&scheduled, async {
                        vec![
                            stage_unit("recovery", wpalt::operations::recovery::tick(&scheduled))
                                .await,
                            stage("publication", content::publish_due(&scheduled)).await,
                            stage("campaigns", wpalt::business::campaigns::tick(&scheduled)).await,
                            stage("commerce", wpalt::commerce::tick(&scheduled)).await,
                            stage("mail", wpalt::business::mail::tick(&scheduled)).await,
                            stage_unit(
                                "engagement-retention",
                                wpalt::business::engagement::cleanup(&scheduled),
                            )
                            .await,
                            stage_unit(
                                "quota-retention",
                                wpalt::business::quotas::cleanup(&scheduled),
                            )
                            .await,
                            stage_unit("maintenance", cleanup(&scheduled)).await,
                        ]
                    })
                    .await
                    .is_err()
                    {
                        tracing::error!(
                            event = "background_history_failed",
                            action = "inspect_site_storage"
                        );
                    }
                }
            });
            let listener = tokio::net::TcpListener::bind(app.config.listen).await?;
            tracing::info!(event="server_started",listen=%app.config.listen);
            axum::serve(
                listener,
                wpalt::web::router(app)
                    .into_make_service_with_connect_info::<std::net::SocketAddr>(),
            )
            .with_graceful_shutdown(shutdown())
            .await?;
            job.abort();
        }
    }
    Ok(())
}

async fn shutdown() {
    #[cfg(unix)]
    {
        let mut terminate =
            tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
                .expect("signal handler");
        tokio::select! {_=tokio::signal::ctrl_c()=>{},_=terminate.recv()=>{}}
    }
    #[cfg(not(unix))]
    {
        let _ = tokio::signal::ctrl_c().await;
    }
}
async fn cleanup(app: &App) -> wpalt::error::Result<()> {
    let _guard = app.mutation().await;
    sqlx::query("DELETE FROM sessions WHERE expires_at<$1")
        .bind(wpalt::now())
        .execute(&app.db.pool)
        .await?;
    sqlx::query("DELETE FROM comment_limits WHERE last_at<$1")
        .bind(wpalt::now() - 86400)
        .execute(&app.db.pool)
        .await?;
    Ok(())
}
async fn seed(app: &App, count: u32) -> anyhow::Result<()> {
    use sqlx::Row;
    anyhow::ensure!((1..=10000).contains(&count), "demo posts must be 1..10000");
    let n: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM posts")
        .fetch_one(&app.db.pool)
        .await?;
    anyhow::ensure!(n == 0, "demo seed requires an empty content library");
    let r = sqlx::query(
        "SELECT id,email,name,role FROM users WHERE role='admin' ORDER BY created_at LIMIT 1",
    )
    .fetch_one(&app.db.pool)
    .await?;
    let s = Session {
        user: User {
            id: r.get("id"),
            email: r.get("email"),
            name: r.get("name"),
            role: r.get("role"),
        },
        csrf: String::new(),
        hash: String::new(),
    };
    let default_language = wpalt::discovery::load(app)
        .await
        .map_err(|e| anyhow::anyhow!(e.1))?
        .0
        .default_language;
    let stories = [
        (
            "A quieter place on the web",
            "Our digital spaces should feel like places we own. A little slower, more considered, and built around the stories we want to tell.",
        ),
        (
            "Notes from the garden",
            "Good things take root with a little patience. These are the things we have been making, reading and learning.",
        ),
        (
            "Building with intention",
            "A small website can do a lot. Start with clear words, thoughtful structure and tools that stay out of the way.",
        ),
        (
            "A field guide to independent publishing",
            "Own your words, your audience and your archives. Publishing should not require a collection of accounts to keep your site running.",
        ),
    ];
    sqlx::query("UPDATE settings SET title='The Local Journal',description='Ideas, field notes and a quieter corner of the independent web.',navigation=$1 WHERE id=1").bind(r#"[{"label":"About","url":"/about"}]"#).execute(&app.db.pool).await?;
    for i in 0..count {
        let (title, lead) = stories[i as usize % stories.len()];
        content::save(app,&s,None,PostInput{import_markdown:false,document:String::new(),locale:default_language.clone(),translation_group:String::new(),seo:"{}".into(),title:if i<4{title.into()}else{format!("{title} · {}",i+1)},slug:format!("journal-{}",i+1),kind:"post".into(),body:format!("{lead}\n\n## Room to think\n\nThis is a working wpalt example: structured content, a shared theme and a publishing workflow you can run on your own server.\n\n- Draft and preview before publishing.\n- Keep unfinished changes away from your live pages.\n- Back up your content and take it with you.\n\n> Useful tools should make good work easier.\n\n### What comes next\n\nExplore the administration panel, edit this story, and switch between the Paper and Ink themes."),fields:serde_json::json!({"subtitle":lead,"reading_minutes":3,"featured":i==0}).to_string(),blocks:r#"[{"kind":"callout","text":"Your content. Your server. No vendor account."}]"#.into(),categories:"Field notes".into(),tags:"Independent web, Publishing".into(),taxonomies:"{}".into(),version:0,action:"publish".into(),publish_at:0,csrf:String::new()}).await.map_err(|e|anyhow::anyhow!(e.1))?;
    }
    content::save(app,&s,None,PostInput{import_markdown:false,document:String::new(),locale:default_language.clone(),translation_group:String::new(),seo:"{}".into(),title:"About the journal".into(),slug:"about".into(),kind:"page".into(),body:"# A home for our ideas\n\nThis journal is an example website running entirely on wpalt. It is small by design, with room to grow.\n\nUse the admin panel to change the navigation, theme and content. Everything here stays on your server.".into(),fields:"{}".into(),blocks:"[]".into(),categories:String::new(),tags:String::new(),taxonomies:"{}".into(),version:0,action:"publish".into(),publish_at:0,csrf:String::new()}).await.map_err(|e|anyhow::anyhow!(e.1))?;
    optimize_bulk(app).await;
    println!("Created {count} stories and an about page.");
    Ok(())
}

async fn optimize_bulk(app: &App) {
    if let Err(error) = app.db.optimize_after_bulk_write().await {
        tracing::warn!(event = "bulk_maintenance_failed", error = %error,
            "Content was committed; database maintenance should be retried by the operator");
    }
}

async fn recovery_bytes(
    config: &Config,
    input: &std::path::Path,
    key_path: Option<&std::path::Path>,
) -> anyhow::Result<Vec<u8>> {
    let encoded = backup::read_bounded(
        input,
        config.max_backup_bytes + wpalt::operations::encryption::OVERHEAD,
    )
    .await
    .map_err(|e| anyhow::anyhow!(e.1))?;
    let Some(path) = key_path else {
        return Ok(encoded);
    };
    let key = wpalt::operations::encryption::read_key(path)
        .await
        .map_err(|e| anyhow::anyhow!(e.1))?;
    let decoded = wpalt::operations::encryption::open(&key, &encoded, config.max_backup_bytes)
        .map_err(|e| anyhow::anyhow!(e.1))?;
    if wpalt::operations::incremental::is_manifest(&decoded) {
        Ok(wpalt::operations::incremental::assemble(
            input.parent().unwrap_or(std::path::Path::new(".")),
            &key,
            &decoded,
            config.max_backup_bytes,
        )
        .await
        .map_err(|e| anyhow::anyhow!(e.1))?)
    } else {
        Ok(decoded)
    }
}
